### ISSUE TITLE
Server-side Integration

### ISSUE THREAD

**Issue by pudgereyem** [segment-integrations/analytics.js-integration-inspectlet#7]
## Background
I'm doing `identify` calls from the server side, which holds all the `traits` associated with that user. From the browser (front end) I only call `identify` with the userId.

## Problem
Since Inspectlet doesn't have a server-side integration, I don't get the traits on their end. I only get `userId`. See screenshot of how it looks in Inspectlet; http://pudge.se/6QVDEu

## Solution
They have an API. I think it would be a good idea to involve the creators of Inspectlet, so we get things rights. Please read the quote below from https://www.inspectlet.com/docs/custom_metrics

> Inspectlet can gather data for Custom Metrics from the server by a standard HTTP GET request. Please note that for server-side metrics, the scope can only be event. Syntax for server-side request: 
>
> https://www.inspectlet.com/cmetrics/api/(wid)?mid=(mid)&name=(name)&value=(value) 
> Not all variables in the URL are necessary. See above for more information about the parameters.

**Comment by pudgereyem** [comment]
Any thoughts on how we can fix this @ndhoule and @hankim813?

Ping @inspectlet

**Comment by hankim813** [comment]
@pudgereyem hey! that is correct we do not have a server side integration for inspectlet at the moment. I'm not sure if they have a public server side api. If they do you can submit a request for an integration at https://segment.com/contact/requests/integration

**Comment by pudgereyem** [comment]
@hankim813 Submitted. I've also updated this issue with the same description as in the request.

@inspectlet would be awesome if you could join this conversation. Could you tell us more about the API and the possibilities?

Thanks!

**Comment by pudgereyem** [comment]
Hey @hankim813 @inspectlet, has there been any development on this?

/Victor

**Comment by inspectlet** [comment]
We do! We'd be happy to help put together a server side integration that leverages our latest [Inspectlet API](https://apidocs.inspectlet.com/). Please let us know if we can be of any help!

**Comment by pudgereyem** [comment]
@hankim813 what would be needed from Inspectlet and Segment respectively to make this happen? 

ping @inspectlet

**Comment by hankim813** [comment]
@inspectlet @pudgereyem we would need to prioritize it internally. right now we have a pretty large backlog for the remainder of this quarter. a server side integration with inspectlet is not something we have slated yet unfortunately.

@inspectlet did you by any chance fill this form out already? https://segment.com/requests/integrations

if not, that's the first step to getting your request into our internal system. I will say right now that in order to be prioritized, we need evidence that there is a large customer demand for this so providing as much stats/context around that will help us prioritize! @pudgereyem ^ you can also fill out the form as we take into consideration just sheer number of customers completing the above form for a given partner.

**Comment by pudgereyem** [comment]
I filled out the form @hankim813.
I understand that you have to prioritise. Is this is the backlog or will you ignore it until you get more requests?

**Comment by hankim813** [comment]
@pudgereyem yes, we have a very large backlog (from the form you filled), I'd say your best bet to get an integration prioritized is have your biggest mutual customers to contact their Segment reps to get this prioritized. Sorry, not trying to ignore you guys! 😥
